services:
  blogserver:
    build: .
    container_name: blogserver
    privileged: true
    volumes:
      - home_data:/home
      - etc_data:/etc
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  home_data:
  etc_data:
