services:
  cse:
    build: 
      context: .
      dockerfile: cse_dockerfile
  eee:
    build:
      context: .
      dockerfile: eee_dockerfile
  mech:
    build:
      context: .
      dockerfile: mech_dockerfile
  apache:
    build:
      context: .
      dockerfile: apache_dockerfile
    ports:
      - "20000:80"
  app:
    build:
      context: .
      dockerfile: app_dockerfile
    ports:
      - "20001:80"
  
